name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .
        cp -r "/content/essentials/python/introduction/img" "_build/html/content/essentials/python/introduction/img"
        cp -r "/content/essentials/python/controlflow/img" "_build/html/content/essentials/python/controlflow/img"
        cp -r "/content/essentials/python/functions/img" "_build/html/content/essentials/python/functions/img"
        cp -r "/content/essentials/python/files/img" "_build/html/content/essentials/python/files/img"
        cp -r "/content/essentials/python/objects/img" "_build/html/content/essentials/python/objects/img"
        cp -r "/content/essentials/python/advanced/img" "_build/html/content/essentials/python/advanced/img"
        cp -r "/content/essentials/python/datetime/img" "_build/html/content/essentials/python/datetime/img"

    # Push the book's HTML to github-pages./docs/_myfolder/${foldername}.md
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
