name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4.1.1

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build . --all
        
    # copy artifacts
    - name: copy artifacts
      run: |
        cp -r "./content/essentials/python/introduction/img" "_build/html/content/essentials/python/introduction/img"
        cp -r "./content/essentials/python/controlflow/img" "_build/html/content/essentials/python/controlflow/img"
        cp -r "./content/essentials/python/functions/img" "_build/html/content/essentials/python/functions/img"
        cp -r "./content/essentials/python/files/img" "_build/html/content/essentials/python/files/img"
        cp -r "./content/essentials/python/objects/img" "_build/html/content/essentials/python/objects/img"
        cp -r "./content/essentials/python/advanced/img" "_build/html/content/essentials/python/advanced/img"
        cp -r "./content/essentials/python/datetime/img" "_build/html/content/essentials/python/datetime/img"
          
    # Push the book's HTML to github-pages./docs/_myfolder/${foldername}.md
    - name: GitHub Pages action
      uses: actions/deploy-pages@v4.0.4
      # with:
        # token: ${{ secrets.GITHUB_TOKEN }}
        # artifact_name: ./_build/html
